import { bannerImage, defaultAvt } from "@/assets/exportImage";
import {
  AccountEntity,
  IngredientEntity,
  OccasionEntity,
  RecipeEntity,
} from "./type";

export const recipes: RecipeEntity[] = [
  {
    id: 1,
    name: "Recipe 1",
    rating: 4.5,
    totalTime: 60,
    active_time: 30,
    serving_size: 4,
    introduction: "This is recipe 1",
    author_note: "Author's note for recipe 1",
    is_private: false,
    image: "recipe1.jpg",
    author: 10,
    nutrition_info_id: 201,
    created_at: new Date(),
  },
  {
    id: 2,
    name: "Recipe 2",
    rating: 3.8,
    totalTime: 45,
    active_time: 20,
    serving_size: 2,
    introduction: "This is recipe 2",
    author_note: "Author's note for recipe 2",
    is_private: true,
    image: "recipe2.jpg",
    author: 9,
    nutrition_info_id: 202,
    created_at: new Date(),
  },
  {
    id: 3,
    name: "Recipe 3",
    rating: 4.2,
    totalTime: 75,
    active_time: 40,
    serving_size: 3,
    introduction: "This is recipe 3",
    author_note: "Author's note for recipe 3",
    is_private: false,
    image: "recipe3.jpg",
    author: 8,
    nutrition_info_id: 203,
    created_at: new Date(),
  },
  {
    id: 4,
    name: "Recipe 4",
    rating: 3.5,
    totalTime: 90,
    active_time: 50,
    serving_size: 6,
    introduction: "This is recipe 4",
    author_note: "Author's note for recipe 4",
    is_private: true,
    image: "recipe4.jpg",
    author: 7,
    nutrition_info_id: 204,
    created_at: new Date(),
  },
  {
    id: 5,
    name: "Recipe 5",
    rating: 4.0,
    totalTime: 55,
    active_time: 25,
    serving_size: 2,
    introduction: "This is recipe 5",
    author_note: "Author's note for recipe 5",
    is_private: false,
    image: "recipe5.jpg",
    author: 6,
    nutrition_info_id: 205,
    created_at: new Date(),
  },
  {
    id: 6,
    name: "Recipe 6",
    rating: 4.8,
    totalTime: 120,
    active_time: 60,
    serving_size: 8,
    introduction: "This is recipe 6",
    author_note: "Author's note for recipe 6",
    is_private: false,
    image: "recipe6.jpg",
    author: 5,
    nutrition_info_id: 206,
    created_at: new Date(),
  },
  {
    id: 7,
    name: "Recipe 7",
    rating: 3.2,
    totalTime: 30,
    active_time: 15,
    serving_size: 1,
    introduction: "This is recipe 7",
    author_note: "Author's note for recipe 7",
    is_private: true,
    image: "recipe7.jpg",
    author: 4,
    nutrition_info_id: 207,
    created_at: new Date(),
  },
  {
    id: 8,
    name: "Recipe 8",
    rating: 4.6,
    totalTime: 70,
    active_time: 35,
    serving_size: 4,
    introduction: "This is recipe 8",
    author_note: "Author's note for recipe 8",
    is_private: false,
    image: "recipe8.jpg",
    author: 1,
    nutrition_info_id: 208,
    created_at: new Date(),
  },
  {
    id: 9,
    name: "Recipe 9",
    rating: 3.7,
    totalTime: 50,
    active_time: 25,
    serving_size: 3,
    introduction: "This is recipe 9",
    author_note: "Author's note for recipe 9",
    is_private: true,
    image: "recipe9.jpg",
    author: 2,
    nutrition_info_id: 209,
    created_at: new Date(),
  },
  {
    id: 10,
    name: "Recipe 10",
    rating: 4.4,
    totalTime: 80,
    active_time: 45,
    serving_size: 5,
    introduction: "This is recipe 10",
    author_note: "Author's note for recipe 10",
    is_private: false,
    image: "recipe10.jpg",
    author: 3,
    nutrition_info_id: 210,
    created_at: new Date(),
  },
];

export const ingredients: IngredientEntity[] = [
  {
    id: 1,
    name: "Bơ",
    image: "image_url_1",
    measurement_unit_id: 1,
    type_id: 1,
    nutrition_info_id: 1,
    isLiquid: true,
    ratio: 0.5,
  },
  {
    id: 2,
    name: "Táo",
    image: "image_url_2",
    measurement_unit_id: 2,
    type_id: 2,
    nutrition_info_id: 2,
    isLiquid: false,
    ratio: 0.75,
  },
  {
    id: 3,
    name: "Chuối",
    image: "image_url_3",
    measurement_unit_id: 3,
    type_id: 3,
    nutrition_info_id: 3,
    isLiquid: true,
    ratio: 0.6,
  },
  {
    id: 4,
    name: "Ổi",
    image: "image_url_4",
    measurement_unit_id: 4,
    type_id: 4,
    nutrition_info_id: 4,
    isLiquid: false,
    ratio: 0.9,
  },
  {
    id: 5,
    name: "Ingredient 5",
    image: "image_url_5",
    measurement_unit_id: 5,
    type_id: 5,
    nutrition_info_id: 5,
    isLiquid: true,
    ratio: 0.7,
  },
  {
    id: 6,
    name: "Ingredient 6",
    image: "image_url_6",
    measurement_unit_id: 6,
    type_id: 6,
    nutrition_info_id: 6,
    isLiquid: false,
    ratio: 0.8,
  },
  {
    id: 7,
    name: "Ingredient 7",
    image: "image_url_7",
    measurement_unit_id: 7,
    type_id: 7,
    nutrition_info_id: 7,
    isLiquid: true,
    ratio: 0.4,
  },
  {
    id: 8,
    name: "Ingredient 8",
    image: "image_url_8",
    measurement_unit_id: 8,
    type_id: 8,
    nutrition_info_id: 8,
    isLiquid: false,
    ratio: 0.65,
  },
  {
    id: 9,
    name: "Ingredient 9",
    image: "image_url_9",
    measurement_unit_id: 9,
    type_id: 9,
    nutrition_info_id: 9,
    isLiquid: true,
    ratio: 0.55,
  },
  {
    id: 10,
    name: "Ingredient 10",
    image: "image_url_10",
    measurement_unit_id: 10,
    type_id: 10,
    nutrition_info_id: 10,
    isLiquid: false,
    ratio: 0.85,
  },
];

export const occasions: OccasionEntity[] = [
  {
    id: 1,
    name: "Tết Nguyên Đán",
    description: "Lễ Tết truyền thống của Việt Nam",
    start_at: new Date(new Date().getFullYear(), 0, 1),
    image: bannerImage,
  },
  {
    id: 2,
    name: "Ngày Quốc khánh",
    description: "Ngày Quốc khánh Việt Nam",
    start_at: new Date(new Date().getFullYear(), 8, 2),
    image: bannerImage,
  },
  {
    id: 3,
    name: "Ngày Lao động",
    description: "Lễ Quốc tế lao động",
    start_at: new Date(new Date().getFullYear(), 4, 1),
    image: bannerImage,
  },
  {
    id: 4,
    name: "Ngày Quốc tế Phụ nữ",
    description: "Ngày Quốc tế của Phụ nữ",
    start_at: new Date(new Date().getFullYear(), 2, 8),
    image: bannerImage,
  },
  {
    id: 5,
    name: "Ngày Quốc tế Hạnh phúc",
    description: "Ngày Quốc tế Hạnh phúc",
    start_at: new Date(new Date().getFullYear(), 2, 20),
    image: bannerImage,
  },
  {
    id: 6,
    name: "Ngày Quốc tế Thiếu nhi",
    description: "Ngày Quốc tế Thiếu nhi",
    start_at: new Date(new Date().getFullYear(), 5, 1),
    image: bannerImage,
  },
  {
    id: 7,
    name: "Ngày Quốc tế Dân số",
    description: "Ngày Quốc tế Dân số",
    start_at: new Date(new Date().getFullYear(), 6, 11),
    image: bannerImage,
  },
  {
    id: 8,
    name: "Ngày Quốc tế Hòa bình",
    description: "Ngày Quốc tế Hòa bình",
    start_at: new Date(new Date().getFullYear(), 8, 21),
    image: bannerImage,
  },
  {
    id: 9,
    name: "Ngày Quốc tế Người cao tuổi",
    description: "Ngày Quốc tế Người cao tuổi",
    start_at: new Date(new Date().getFullYear(), 9, 1),
    image: bannerImage,
  },
  {
    id: 10,
    name: "Ngày Quốc tế Áo trắng",
    description: "Ngày Quốc tế Áo trắng",
    start_at: new Date(new Date().getFullYear(), 4, 5),
    image: bannerImage,
  },
];

export const accounts: AccountEntity[] = [
  {
    id: 1,
    username: "nguoidung1",
    password: "matkhau1",
    name: "Người Dùng Một",
    avatar: defaultAvt,
    introduction:
      "Lorem Ipsum chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành công nghiệp in ấn từ những năm 1500, khi một họa sĩ vô danh ghép nhiều đoạn văn bản với nhau để tạo thành một bản mẫu văn bản.",
  },
  {
    id: 2,
    username: "nguoidung2",
    password: "matkhau2",
    name: "Người Dùng Hai",
    avatar: defaultAvt,
    introduction:
      "Lorem Ipsum chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành công nghiệp in ấn từ những năm 1500, khi một họa sĩ vô danh ghép nhiều đoạn văn bản với nhau để tạo thành một bản mẫu văn bản.",
  },
  {
    id: 3,
    username: "nguoidung3",
    password: "matkhau3",
    name: "Người Dùng Ba",
    avatar: defaultAvt,
    introduction:
      "Lorem Ipsum chỉ đơn giản là một đoạn văn bản giả, được dùng vào việc trình bày và dàn trang phục vụ cho in ấn. Lorem Ipsum đã được sử dụng như một văn bản chuẩn cho ngành công nghiệp in ấn từ những năm 1500, khi một họa sĩ vô danh ghép nhiều đoạn văn bản với nhau để tạo thành một bản mẫu văn bản.",
  },
  {
    id: 4,
    username: "nguoidung4",
    password: "matkhau4",
    name: "Người Dùng Bốn",
    avatar: defaultAvt,
    introduction: "Xin chào mọi người, tôi là Người Dùng Bốn.",
  },
  {
    id: 5,
    username: "nguoidung5",
    password: "matkhau5",
    name: "Người Dùng Năm",
    avatar: defaultAvt,
    introduction: "Chúc mọi người một ngày tốt lành! Tôi là Người Dùng Năm.",
  },
  {
    id: 6,
    username: "nguoidung6",
    password: "matkhau6",
    name: "Người Dùng Sáu",
    avatar: defaultAvt,
    introduction: "Rất vui được gặp bạn. Tôi là Người Dùng Sáu.",
  },
  {
    id: 7,
    username: "nguoidung7",
    password: "matkhau7",
    name: "Người Dùng Bảy",
    avatar: defaultAvt,
    introduction: "Chào bạn, tôi là Người Dùng Bảy.",
  },
  {
    id: 8,
    username: "nguoidung8",
    password: "matkhau8",
    name: "Người Dùng Tám",
    avatar: defaultAvt,
    introduction: "Xin chào, tôi là Người Dùng Tám.",
  },
  {
    id: 9,
    username: "nguoidung9",
    password: "matkhau9",
    name: "Người Dùng Chín",
    avatar: defaultAvt,
    introduction: "Chúc mọi người một ngày vui vẻ! Tôi là Người Dùng Chín.",
  },
  {
    id: 10,
    username: "nguoidung10",
    password: "matkhau10",
    name: "Người Dùng Mười",
    avatar: defaultAvt,
    introduction: "Rất vui được làm quen với bạn. Tôi là Người Dùng Mười.",
  },
];
