import { RecipeEntity } from "./type";

export const recipes: RecipeEntity[] = [
  {
    id: 1,
    name: "Recipe 1",
    rating: 4.5,
    totalTime: 60,
    active_time: 30,
    serving_size: 4,
    introduction: "This is recipe 1",
    author_note: "Author's note for recipe 1",
    is_private: false,
    image: "recipe1.jpg",
    author: 101,
    nutrition_info_id: 201,
  },
  {
    id: 2,
    name: "Recipe 2",
    rating: 3.8,
    totalTime: 45,
    active_time: 20,
    serving_size: 2,
    introduction: "This is recipe 2",
    author_note: "Author's note for recipe 2",
    is_private: true,
    image: "recipe2.jpg",
    author: 102,
    nutrition_info_id: 202,
  },
  {
    id: 3,
    name: "Recipe 3",
    rating: 4.2,
    totalTime: 75,
    active_time: 40,
    serving_size: 3,
    introduction: "This is recipe 3",
    author_note: "Author's note for recipe 3",
    is_private: false,
    image: "recipe3.jpg",
    author: 103,
    nutrition_info_id: 203,
  },
  {
    id: 4,
    name: "Recipe 4",
    rating: 3.5,
    totalTime: 90,
    active_time: 50,
    serving_size: 6,
    introduction: "This is recipe 4",
    author_note: "Author's note for recipe 4",
    is_private: true,
    image: "recipe4.jpg",
    author: 104,
    nutrition_info_id: 204,
  },
  {
    id: 5,
    name: "Recipe 5",
    rating: 4.0,
    totalTime: 55,
    active_time: 25,
    serving_size: 2,
    introduction: "This is recipe 5",
    author_note: "Author's note for recipe 5",
    is_private: false,
    image: "recipe5.jpg",
    author: 105,
    nutrition_info_id: 205,
  },
  {
    id: 6,
    name: "Recipe 6",
    rating: 4.8,
    totalTime: 120,
    active_time: 60,
    serving_size: 8,
    introduction: "This is recipe 6",
    author_note: "Author's note for recipe 6",
    is_private: false,
    image: "recipe6.jpg",
    author: 106,
    nutrition_info_id: 206,
  },
  {
    id: 7,
    name: "Recipe 7",
    rating: 3.2,
    totalTime: 30,
    active_time: 15,
    serving_size: 1,
    introduction: "This is recipe 7",
    author_note: "Author's note for recipe 7",
    is_private: true,
    image: "recipe7.jpg",
    author: 107,
    nutrition_info_id: 207,
  },
  {
    id: 8,
    name: "Recipe 8",
    rating: 4.6,
    totalTime: 70,
    active_time: 35,
    serving_size: 4,
    introduction: "This is recipe 8",
    author_note: "Author's note for recipe 8",
    is_private: false,
    image: "recipe8.jpg",
    author: 108,
    nutrition_info_id: 208,
  },
  {
    id: 9,
    name: "Recipe 9",
    rating: 3.7,
    totalTime: 50,
    active_time: 25,
    serving_size: 3,
    introduction: "This is recipe 9",
    author_note: "Author's note for recipe 9",
    is_private: true,
    image: "recipe9.jpg",
    author: 109,
    nutrition_info_id: 209,
  },
  {
    id: 10,
    name: "Recipe 10",
    rating: 4.4,
    totalTime: 80,
    active_time: 45,
    serving_size: 5,
    introduction: "This is recipe 10",
    author_note: "Author's note for recipe 10",
    is_private: false,
    image: "recipe10.jpg",
    author: 110,
    nutrition_info_id: 210,
  },
];

// Now, the 'recipes' array contains 10 items of type RecipeEntity
